"""create table code verification

Revision ID: 0129a6aaf6a5
Revises: 062eb665bdb8
Create Date: 2021-04-24 20:19:34.017407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0129a6aaf6a5'
down_revision = '062eb665bdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_verification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_verification')
    # ### end Alembic commands ###
