"""add table image

Revision ID: 062eb665bdb8
Revises: 51c13890b075
Create Date: 2021-04-24 16:16:31.739870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062eb665bdb8'
down_revision = '51c13890b075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
