"""nullable column

Revision ID: 1c2876c32a15
Revises: 7e8c3a0e3d62
Create Date: 2021-04-25 19:55:42.026743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2876c32a15'
down_revision = '7e8c3a0e3d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servico_image', 'descricao',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servico_image', 'descricao',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
