"""renomeando colunas

Revision ID: 1f24e842142c
Revises: ea48faee7a08
Create Date: 2021-03-07 16:09:47.449127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f24e842142c'
down_revision = 'ea48faee7a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('municipio_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('endereco_municipioId_fkey', 'endereco', type_='foreignkey')
    op.create_foreign_key(None, 'endereco', 'municipio', ['municipio_id'], ['id'])
    op.drop_column('endereco', 'municipioId')
    op.add_column('municipio', sa.Column('estado_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('municipio_estadoId_fkey', 'municipio', type_='foreignkey')
    op.create_foreign_key(None, 'municipio', 'estado', ['estado_id'], ['id'])
    op.drop_column('municipio', 'estadoId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipio', sa.Column('estadoId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'municipio', type_='foreignkey')
    op.create_foreign_key('municipio_estadoId_fkey', 'municipio', 'estado', ['estadoId'], ['id'])
    op.drop_column('municipio', 'estado_id')
    op.add_column('endereco', sa.Column('municipioId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'endereco', type_='foreignkey')
    op.create_foreign_key('endereco_municipioId_fkey', 'endereco', 'municipio', ['municipioId'], ['id'])
    op.drop_column('endereco', 'municipio_id')
    # ### end Alembic commands ###
