"""adicionando coluna descricao

Revision ID: 2d62525598b7
Revises: 05cf39e5f41f
Create Date: 2021-02-16 23:10:26.030676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d62525598b7'
down_revision = '05cf39e5f41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tecido', sa.Column('descricao', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tecido', 'descricao')
    # ### end Alembic commands ###
