"""adicionando coluna valor frete

Revision ID: 383d7657512c
Revises: 571da5d1c6e9
Create Date: 2021-04-15 19:49:29.497974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383d7657512c'
down_revision = '571da5d1c6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('valorFrete', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'valorFrete')
    # ### end Alembic commands ###
