"""adicionando tipo de servico

Revision ID: 3f907ab649a1
Revises: b334247c5ba3
Create Date: 2021-05-19 22:34:57.613627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f907ab649a1'
down_revision = 'b334247c5ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_servico', sa.Column('descricao', sa.String(length=100), nullable=False))
    op.drop_column('tipo_servico', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_servico', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('tipo_servico', 'descricao')
    # ### end Alembic commands ###
