"""add table image

Revision ID: 51c13890b075
Revises: b0460f60a76a
Create Date: 2021-04-24 15:55:03.991525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c13890b075'
down_revision = 'b0460f60a76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.Column('ext', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('image_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'image', ['image_id'], ['id'])
    op.drop_column('usuario', 'img_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('img_path', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'image_id')
    op.drop_table('image')
    # ### end Alembic commands ###
