"""criando servico pagamento

Revision ID: 571da5d1c6e9
Revises: bd07d7a60407
Create Date: 2021-04-08 18:38:03.381078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571da5d1c6e9'
down_revision = 'bd07d7a60407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico_pagamento',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('forma_pagamento_id', sa.BigInteger(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('servico_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servico_pagamento')
    # ### end Alembic commands ###
