"""add coluna fisica_juridica e cnpjj

Revision ID: 5cab1c0eaead
Revises: 679f624bee72
Create Date: 2021-05-20 20:30:36.399245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cab1c0eaead'
down_revision = '679f624bee72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('cnpj', sa.String(length=20), nullable=True))
    op.add_column('cliente', sa.Column('fisica_juridica', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'fisica_juridica')
    op.drop_column('cliente', 'cnpj')
    # ### end Alembic commands ###
