"""removendo coluna status 

Revision ID: 679f624bee72
Revises: c23bdda83919
Create Date: 2021-05-20 18:02:52.892921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679f624bee72'
down_revision = 'c23bdda83919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fluxo_caixa', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fluxo_caixa', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
