"""empty message

Revision ID: 7acae31a67ca
Revises: 5cab1c0eaead
Create Date: 2021-05-20 22:19:15.327833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acae31a67ca'
down_revision = '5cab1c0eaead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico_pagamento', sa.Column('data', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico_pagamento', 'data')
    # ### end Alembic commands ###
