"""corrigindo nome de coluna

Revision ID: 7e35c25254d5
Revises: 383d7657512c
Create Date: 2021-04-15 19:50:10.685974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e35c25254d5'
down_revision = '383d7657512c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('valor_frete', sa.Float(), nullable=True))
    op.drop_column('servico', 'valorFrete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('valorFrete', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('servico', 'valor_frete')
    # ### end Alembic commands ###
