"""adicionando table servico image

Revision ID: 7e8c3a0e3d62
Revises: cbdf9d256753
Create Date: 2021-04-25 19:10:30.855007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8c3a0e3d62'
down_revision = 'cbdf9d256753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('servico_id', sa.BigInteger(), nullable=True),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servico_image')
    # ### end Alembic commands ###
