"""create table muncipio e endereco

Revision ID: 9bdae2700dfe
Revises: ad86a7d6571f
Create Date: 2021-02-17 21:23:22.395291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdae2700dfe'
down_revision = 'ad86a7d6571f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipio',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estado_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estado_id', sa.BigInteger(), nullable=True),
    sa.Column('municipio_id', sa.BigInteger(), nullable=True),
    sa.Column('cep', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('complemento', sa.String(length=30), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    op.drop_table('municipio')
    # ### end Alembic commands ###
