"""create table estado

Revision ID: ad86a7d6571f
Revises: d90204081d09
Create Date: 2021-02-17 21:09:28.222272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad86a7d6571f'
down_revision = 'd90204081d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sigla', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado')
    # ### end Alembic commands ###
