"""add columns

Revision ID: b0460f60a76a
Revises: e0f27b6b240c
Create Date: 2021-04-20 14:54:47.099548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0460f60a76a'
down_revision = 'e0f27b6b240c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('materiais_utilizados', sa.String(length=300), nullable=True))
    op.add_column('servico', sa.Column('observacao', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'observacao')
    op.drop_column('servico', 'materiais_utilizados')
    # ### end Alembic commands ###
