"""Tabela de cores

Revision ID: baaeea8294a1
Revises: f60a67e9561b
Create Date: 2021-02-07 23:41:46.897867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaeea8294a1'
down_revision = 'f60a67e9561b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('sta', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cor')
    # ### end Alembic commands ###
