"""adicionando colunas na tabela usuario

Revision ID: cbdf9d256753
Revises: 0129a6aaf6a5
Create Date: 2021-04-24 23:06:17.841298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdf9d256753'
down_revision = '0129a6aaf6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('usuario', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('usuario', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usuario', 'usuario', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'status')
    op.drop_column('usuario', 'date_updated')
    op.drop_column('usuario', 'date_created')
    op.drop_column('usuario', 'created_by')
    # ### end Alembic commands ###
