"""adicionando coluna whatsapp

Revision ID: ea48faee7a08
Revises: 9bdae2700dfe
Create Date: 2021-03-07 15:42:35.944137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea48faee7a08'
down_revision = '9bdae2700dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('estadoId', sa.BigInteger(), nullable=True))
    op.add_column('endereco', sa.Column('municipioId', sa.BigInteger(), nullable=True))
    op.drop_constraint('endereco_municipio_id_fkey', 'endereco', type_='foreignkey')
    op.drop_constraint('endereco_estado_id_fkey', 'endereco', type_='foreignkey')
    op.create_foreign_key(None, 'endereco', 'estado', ['estadoId'], ['id'])
    op.create_foreign_key(None, 'endereco', 'municipio', ['municipioId'], ['id'])
    op.drop_column('endereco', 'municipio_id')
    op.drop_column('endereco', 'estado_id')
    op.add_column('municipio', sa.Column('estadoId', sa.BigInteger(), nullable=True))
    op.drop_constraint('municipio_estado_id_fkey', 'municipio', type_='foreignkey')
    op.create_foreign_key(None, 'municipio', 'estado', ['estadoId'], ['id'])
    op.drop_column('municipio', 'estado_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipio', sa.Column('estado_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'municipio', type_='foreignkey')
    op.create_foreign_key('municipio_estado_id_fkey', 'municipio', 'estado', ['estado_id'], ['id'])
    op.drop_column('municipio', 'estadoId')
    op.add_column('endereco', sa.Column('estado_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('endereco', sa.Column('municipio_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'endereco', type_='foreignkey')
    op.drop_constraint(None, 'endereco', type_='foreignkey')
    op.create_foreign_key('endereco_estado_id_fkey', 'endereco', 'estado', ['estado_id'], ['id'])
    op.create_foreign_key('endereco_municipio_id_fkey', 'endereco', 'municipio', ['municipio_id'], ['id'])
    op.drop_column('endereco', 'municipioId')
    op.drop_column('endereco', 'estadoId')
    # ### end Alembic commands ###
