"""renomeando coluna sta

Revision ID: f035d30d7415
Revises: baaeea8294a1
Create Date: 2021-02-07 23:44:42.361082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f035d30d7415'
down_revision = 'baaeea8294a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cor', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('cor', 'sta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cor', sa.Column('sta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cor', 'status')
    # ### end Alembic commands ###
