"""not null - cor

Revision ID: f2bed235d1b0
Revises: f035d30d7415
Create Date: 2021-02-08 00:21:09.475656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bed235d1b0'
down_revision = 'f035d30d7415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cor', 'descricao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cor', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cor', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cor', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cor', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cor', 'descricao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
