"""Adicionando coluna img_path

Revision ID: f60a67e9561b
Revises: 306ec269e16c
Create Date: 2021-02-07 22:57:39.871896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60a67e9561b'
down_revision = '306ec269e16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('img_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'img_path')
    # ### end Alembic commands ###
